/**
 * Home page to access backup database
 * Date : 04.09.19
 * Last Modified: 19.09.19
 */
package Database;
import static Encryption.AESEncryption.decrypt;
import static Encryption.AESEncryption.encrypt;
import java.awt.Color; 
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Fahim
 */
public class backUpHome extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    private String user, adminUser;
    
    public backUpHome(String user, String adminUser) {
        initComponents();
        this.user = user;
        this.adminUser = adminUser;
    }
    
    public backUpHome() {
        initComponents();
    }
    
    private String getTable(String s){
        String table = "";
        if(s.equals("1st Batch")) table = "batch_1";
        else if(s.equals("2nd Batch")) table = "batch_2";
        else if(s.equals("3rd Batch")) table = "batch_3";
        else if(s.equals("4th Batch")) table = "batch_4";
        else if(s.equals("5th Batch")) table = "batch_5";
        else if(s.equals("6th Batch")) table = "batch_6";
        else if(s.equals("7th Batch")) table = "batch_7";
        else if(s.equals("8th Batch")) table = "batch_8";
        else if(s.equals("9th Batch")) table = "batch_9";
        else if(s.equals("10th Batch")) table = "batch_10";
        else if(s.equals("11th Batch")) table = "batch_11";
        else if(s.equals("12th Batch")) table = "batch_12";
        else if(s.equals("13th Batch")) table = "batch_13";
        else if(s.equals("14th Batch")) table = "batch_14";
        else if(s.equals("15th Batch")) table = "batch_15";
        return table;
    }
    
    private String getBackupTable(String s){
        String table = "";
        if(s.equals("1st Batch")) table = "backup_1";
        else if(s.equals("2nd Batch")) table = "backup_2";
        else if(s.equals("3rd Batch")) table = "backup_3";
        else if(s.equals("4th Batch")) table = "backup_4";
        else if(s.equals("5th Batch")) table = "backup_5";
        else if(s.equals("6th Batch")) table = "backup_6";
        else if(s.equals("7th Batch")) table = "backup_7";
        else if(s.equals("8th Batch")) table = "backup_8";
        else if(s.equals("9th Batch")) table = "backup_9";
        else if(s.equals("10th Batch")) table = "backup_10";
        else if(s.equals("11th Batch")) table = "backup_11";
        else if(s.equals("12th Batch")) table = "backup_12";
        else if(s.equals("13th Batch")) table = "backup_13";
        else if(s.equals("14th Batch")) table = "backup_14";
        else if(s.equals("15th Batch")) table = "backup_15";
        return table;
    }
    
    final String secretKey = "I have now secret.";
    
    public ArrayList<User> userList(String database, String table){
        ArrayList<User> userList = new ArrayList<>();
        
        try{
            //Class.forName("com.mysql.jdbc.Driver");
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+database+"?serverTimezone=EST5EDT", "root", "");
                    
            String query = "SELECT * FROM " + table;
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            User user;
            
            while(rs.next()){
                user = new User(rs.getInt("Serial NO."), decrypt(rs.getString("Name"), secretKey), rs.getString("ID"));
                userList.add(user);
            }
            return userList;
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
        return userList;
    }
    
    public void show_user(String database, String table){
        ArrayList<User> list = userList(database,table);
        DefaultTableModel model = (DefaultTableModel)datatable.getModel();
        model.setRowCount(0);
        Object ob[] = new Object[3];
        for(int i = 0; i< list.size(); i++){
            ob[0] = list.get(i).getseial();
            ob[1] = list.get(i).getID();
            ob[2] = list.get(i).getname();
            model.addRow(ob);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dept = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        batch = new javax.swing.JComboBox<>();
        go = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        restore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        dateOfBirth = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        semester = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Backup Home");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/Icon_image/PUST - Copy.png"))); // NOI18N

        jLabel9.setBackground(new Color(255, 255, 255, 128));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Student Database Management System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Department:");

        dept.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "CSE", "EEE", "CE" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Batch:");

        batch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        batch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "1st Batch", "2nd Batch", "3rd Batch", "4th Batch", "5th Batch", "6th Batch", "7th Batch", "8th Batch", "9th Batch", "10th Batch", "11th Batch", "12th Batch", "13th Batch", "14th Batch", "15th Batch" }));

        go.setText("Go");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        datatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index", "ID", "Name"
            }
        ));
        datatable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datatableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(datatable);
        if (datatable.getColumnModel().getColumnCount() > 0) {
            datatable.getColumnModel().getColumn(0).setResizable(false);
            datatable.getColumnModel().getColumn(0).setPreferredWidth(20);
            datatable.getColumnModel().getColumn(1).setResizable(false);
            datatable.getColumnModel().getColumn(1).setPreferredWidth(30);
            datatable.getColumnModel().getColumn(2).setResizable(false);
            datatable.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(batch, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(go, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(go))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/Icon_image/icons8-edit-file-23.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/Icon_image/icons8-delete-23.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        restore.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        restore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/Icon_image/icons8-database-restore-31.png"))); // NOI18N
        restore.setText("Restore");
        restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(restore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(restore, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 130, 270));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Detail Information");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 306, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText(" Student's Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 49, 139, 31));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Date of Birth:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 86, 139, 31));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Gender:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, 139, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Semester:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 160, 139, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("ID number:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 201, 139, 27));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 49, 259, 31));

        dateOfBirth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateOfBirth.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 86, 259, 31));

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 123, 259, 31));

        semester.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        semester.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 160, 259, 31));

        ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 197, 259, 31));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Phone number:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 238, 139, 27));

        phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 234, 259, 31));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Email address:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 275, 139, 27));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 271, 259, 31));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/Icon_image/icons8-go-back-41.png"))); // NOI18N
        back.setText("Go Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
        String database = dept.getItemAt(dept.getSelectedIndex());
        String table = getBackupTable(batch.getItemAt(batch.getSelectedIndex()));
        show_user(database,table);
    }//GEN-LAST:event_goActionPerformed

    private void datatableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datatableMouseClicked
        // TODO add your handling code here:
        int i = datatable.getSelectedRow();
        TableModel model = datatable.getModel();
        String index = model.getValueAt(i, 0).toString();
        
        String database = dept.getItemAt(dept.getSelectedIndex());
        String table = getBackupTable(batch.getItemAt(batch.getSelectedIndex()));
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+database+"?serverTimezone=EST5EDT", "root", "");
            String sql = "SELECT * FROM `"+table+"` WHERE `Serial NO.` = '"+index+"'";
            PreparedStatement p = conn.prepareStatement(sql);
            ResultSet rs = p.executeQuery();
            if(rs.next()){
                name.setText(decrypt(rs.getString("Name"), secretKey));
                ID.setText(rs.getString("ID"));
                gender.setText(decrypt(rs.getString("Gender"), secretKey));
                dateOfBirth.setText(decrypt(rs.getString("Date of Birth"), secretKey));
                semester.setText(decrypt(rs.getString("Semester"), secretKey));
                phone.setText(decrypt(rs.getString("Phone"), secretKey));
                email.setText(decrypt(rs.getString("Email"), secretKey));                
            }
        }catch(Exception ex){ JOptionPane.showMessageDialog(this,ex); }
    }//GEN-LAST:event_datatableMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.YES_NO_OPTION;
            int result_confirm = JOptionPane.showConfirmDialog(this,"Are you sure?","Warning",confirm);
            if(result_confirm == JOptionPane.YES_OPTION){
                new homepage(user, adminUser).setVisible(true);
                dispose();
            }
    }//GEN-LAST:event_backActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        if(dept.getSelectedIndex() == 0 && batch.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this,"You haven't selected any data yet.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (this, "Are you sure you want to delete?\nThere is no way to recover this data.","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    String database = dept.getItemAt(dept.getSelectedIndex());
                    String table = getBackupTable(batch.getItemAt(batch.getSelectedIndex()));
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + database + "?serverTimezone=EST5EDT", "root", "");
                    
                    int i = datatable.getSelectedRow();
                    TableModel model = datatable.getModel();
                    String index = model.getValueAt(i, 0).toString();
                    
                    String query = "DELETE FROM `"+table+"` WHERE `Serial NO.` = " +index;
                    PreparedStatement pstmt = conn.prepareStatement(query);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Operation Successful.");
                                        
                    //  Set the Detail Information fields empty
                    name.setText("");
                    dateOfBirth.setText("");
                    gender.setText("");
                    semester.setText("");
                    ID.setText("");
                    phone.setText("");
                    email.setText("");
                    
                    show_user(database,table);
                    
                }catch(Exception e){ JOptionPane.showMessageDialog(this,e); }
            }
        }
                        
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        if(dept.getSelectedIndex() == 0 && batch.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this,"You haven't selected any data yet.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int dialogResult = JOptionPane.showConfirmDialog (this, "Are you sure you want to update?","Confirm?",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                int i = datatable.getSelectedRow();
                TableModel model = datatable.getModel();
                String index = model.getValueAt(i, 0).toString();
        
                String database = dept.getItemAt(dept.getSelectedIndex());
                String table = getBackupTable(batch.getItemAt(batch.getSelectedIndex()));
                new update(index, database, table, false, user, adminUser).setVisible(true);
                dispose();
            }
        }
        
    }//GEN-LAST:event_updateActionPerformed

    private void restoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreActionPerformed
        // TODO add your handling code here:
        if(dept.getSelectedIndex() == 0 && batch.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this,"You haven't selected any data yet.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (this, "Are you sure you want to restore?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    //Class.forName("com.mysql.jdbc.Driver");
                    String database = dept.getItemAt(dept.getSelectedIndex());
                    String table = getTable(batch.getItemAt(batch.getSelectedIndex()));
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + database + "?serverTimezone=EST5EDT", "root", "");
                    
                    String sql = "insert into " + table + " values (?, ?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement p = conn.prepareStatement(sql);
                    
                    //  set field of auto increment   
                    p.setString(1, null);
                    p.setInt(2, Integer.parseInt(ID.getText()));
                    p.setString(3, encrypt(name.getText(), secretKey));
                    p.setString(4, encrypt(semester.getText(), secretKey));
                    p.setString(5, encrypt(dateOfBirth.getText(), secretKey));
                    p.setString(6, encrypt(gender.getText(), secretKey));
                    p.setString(7, encrypt(phone.getText(), secretKey));
                    p.setString(8, encrypt(email.getText(), secretKey));
                    p.executeUpdate();
                }catch(Exception ex){ JOptionPane.showMessageDialog(this,ex); }
                
                try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    String database = dept.getItemAt(dept.getSelectedIndex());
                    String table = getBackupTable(batch.getItemAt(batch.getSelectedIndex()));
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + database + "?serverTimezone=EST5EDT", "root", "");
                    int i = datatable.getSelectedRow();
                    //i++;
                    TableModel model = datatable.getModel();
                    String index = model.getValueAt(i, 0).toString();
                    
                    String query = "DELETE FROM `"+table+"` WHERE `Serial NO.` = " +index;
                    PreparedStatement pstmt = conn.prepareStatement(query);
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Operation Successful.");
                                        
                    //  Set the Detail Information fields empty
                    name.setText("");
                    dateOfBirth.setText("");
                    gender.setText("");
                    semester.setText("");
                    ID.setText("");
                    phone.setText("");
                    email.setText("");
                    
                    show_user(database,table);
                    
                }catch(Exception e){ JOptionPane.showMessageDialog(this,e); }
            }
        }
    }//GEN-LAST:event_restoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(backUpHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(backUpHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(backUpHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(backUpHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new backUpHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> batch;
    private javax.swing.JTable datatable;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> dept;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gender;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private javax.swing.JButton restore;
    private javax.swing.JLabel semester;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}