/**
 * Student Database Management System User Register Form(2.0)
 * Date : 09.09.19
 * Last Modified: 19.09.19
 */
package Database;

import static Encryption.AESEncryption.encrypt;
import static Encryption.AESEncryption.hashPassword;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.UIManager;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Fahim
 */
public class Register_New extends javax.swing.JFrame {

    /**
     * Creates new form Register_New
     */
    public Register_New() {
        initComponents();
    }
    
    private boolean errorPhone = false, errorEmail = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        newPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        confirmPassword = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        showPassword1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        emailError = new javax.swing.JLabel();
        phoneError = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register New User");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register New User");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Name:");

        name.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        name.setForeground(new java.awt.Color(204, 204, 204));
        name.setText("Enter name");
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Phone:");

        phone.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(204, 204, 204));
        phone.setText("Enter Phome number");
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("User Name:");

        userName.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(204, 204, 204));
        userName.setText("Create user name");
        userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText(" Create Password:");

        newPassword.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        newPassword.setForeground(new java.awt.Color(204, 204, 204));
        newPassword.setText("New password");
        newPassword.setEchoChar((char) 0);
        newPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                newPasswordFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Confirm password:");

        confirmPassword.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        confirmPassword.setForeground(new java.awt.Color(204, 204, 204));
        confirmPassword.setText("Confirm password");
        confirmPassword.setEchoChar((char) 0);
        confirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPasswordFocusLost(evt);
            }
        });

        register.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/Icon_image/icons8-submit-progress-33.png"))); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/Icon_image/icons8-cancel-31.png"))); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        showPassword1.setText("Show password");
        showPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassword1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Email:");

        email.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setText("Enter Email address");
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });

        emailError.setForeground(java.awt.Color.red);
        emailError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        phoneError.setForeground(new java.awt.Color(255, 0, 51));
        phoneError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 52, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userName)
                                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 18, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 198, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showPassword1)
                            .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(phoneError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showPassword1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/Icon_image/PUST - Copy.png"))); // NOI18N

        jLabel9.setBackground(new Color(255, 255, 255, 128));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Student Database Management System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
        if(name.getText().trim().equals("Enter name")){
            name.setText("");
            name.setForeground(Color.black);
            name.setFont(new java.awt.Font("Tahoma", 1, 14));
        }
    }//GEN-LAST:event_nameFocusGained
    void nameFocusLost(){
        if(name.getText().trim().equals("")){
            name.setText("Enter name");
            name.setForeground(new Color(204,204,204));
            name.setFont(new java.awt.Font("Tahoma", 3, 14));
        }
    }
    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
        nameFocusLost();
    }//GEN-LAST:event_nameFocusLost

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        // TODO add your handling code here:
        if(phone.getText().trim().equals("Enter Phome number")){
            phone.setText("");
            phone.setForeground(Color.black);
            phone.setFont(new java.awt.Font("Tahoma", 1, 14));
        }
    }//GEN-LAST:event_phoneFocusGained
    void phoneFocusLost(){
        if(phone.getText().trim().equals("")){
            phone.setText("Enter Phome number");
            phone.setForeground(new Color(204,204,204));
            phone.setFont(new java.awt.Font("Tahoma", 3, 14));
        }
        if(!(phone.getText().trim().equals("Enter Phome number")) && !(phone.getText().trim().equals(""))){
            if (!(phone.getText().contains("017")) && !(phone.getText().contains("019")) && !(phone.getText().contains("018")) && !(phone.getText().contains("016")) && !(phone.getText().contains("015")) && !(phone.getText().contains("014")) && !(phone.getText().contains("013"))){
                phoneError.setText("Invalid phone number.");
                errorPhone = true;
            }
            else if(phone.getText().length() != 11 ){ phoneError.setText("Invalid phone number."); errorPhone = true; }
            else { phoneError.setText(" "); errorPhone = false;}
        }
    }
    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
        // TODO add your handling code here:
        phoneFocusLost();

    }//GEN-LAST:event_phoneFocusLost

    private void userNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusGained
        // TODO add your handling code here:
        if(userName.getText().trim().equals("Create user name")){
            userName.setText("");
            userName.setForeground(Color.black);
            userName.setFont(new java.awt.Font("Tahoma", 1, 14));
        }
    }//GEN-LAST:event_userNameFocusGained
    void userNameFocusLost(){
        if(userName.getText().trim().equals("")){
            userName.setText("Create user name");
            userName.setForeground(new Color(204,204,204));
            userName.setFont(new java.awt.Font("Tahoma", 3, 14));
        }
    }
    private void userNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusLost
        // TODO add your handling code here:
        userNameFocusLost();
        if(!(userName.getText().trim().equals("")) && !(userName.getText().trim().equals("Create user name"))){
            String pass = "";
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cse?serverTimezone=EST5EDT", "root", "");
                String sql = "SELECT * FROM `user_info` WHERE `User_name` = '"+userName.getText().trim()+"'";
                PreparedStatement p = conn.prepareStatement(sql);
                ResultSet rs = p.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this,"User name already present. \nSelect another one.", "Failure", JOptionPane.ERROR_MESSAGE);
                    userName.setText(""); userNameFocusLost();
                }
            }catch(Exception ex){ JOptionPane.showMessageDialog(this,ex); }
        }
    }//GEN-LAST:event_userNameFocusLost

    private void newPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordFocusGained
        // TODO add your handling code here:
        if(String.valueOf(newPassword.getPassword()).trim().equals("New password")) {
            newPassword.setText("");
            newPassword.setForeground(Color.black);
            newPassword.setEchoChar('\u25cf');
            newPassword.setFont(new java.awt.Font("Tahoma", 1, 14));
        }
    }//GEN-LAST:event_newPasswordFocusGained
    void newPasswordFocusLost(){
        if(String.valueOf(newPassword.getPassword()).trim().equals("")) {
            newPassword.setText("New password");
            newPassword.setForeground(new Color(204,204,204));
            newPassword.setEchoChar((char) 0);
            newPassword.setFont(new java.awt.Font("Tahoma", 3, 14));
        }
    }
    private void newPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordFocusLost
        // TODO add your handling code here:
        newPasswordFocusLost();
    }//GEN-LAST:event_newPasswordFocusLost

    private void confirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordFocusGained
        // TODO add your handling code here:
        if(String.valueOf(confirmPassword.getPassword()).trim().equals("Confirm password")) {
            confirmPassword.setText("");
            confirmPassword.setForeground(Color.black);
            confirmPassword.setEchoChar('\u25cf');
            confirmPassword.setFont(new java.awt.Font("Tahoma", 1, 14));
        }
    }//GEN-LAST:event_confirmPasswordFocusGained
    void confirmPasswordFocusLost(){
        if(String.valueOf(confirmPassword.getPassword()).trim().equals("")) {
            confirmPassword.setText("Confirm password");
            confirmPassword.setForeground(new Color(204,204,204));
            confirmPassword.setEchoChar((char) 0);
            confirmPassword.setFont(new java.awt.Font("Tahoma", 3, 14));
        }
    }
    private void confirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordFocusLost
        // TODO add your handling code here:
        confirmPasswordFocusLost();
    }//GEN-LAST:event_confirmPasswordFocusLost

    final String secretKey = "I have now secret.";
    
    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        
        if(name.getText().equals("Enter name") || phone.getText().equals("Enter Phome number") || userName.getText().equals("Create user name") || newPassword.getPassword().equals("New password") || confirmPassword.getPassword().equals("Confirm password") || email.getText().equals("Enter Email address")){
            JOptionPane.showMessageDialog(this,"You haven't filled all the fields.", "Failure", JOptionPane.ERROR_MESSAGE);
        }
        else if(errorEmail){
            JOptionPane.showMessageDialog(this,"Please enter correct Email.", "Failure", JOptionPane.ERROR_MESSAGE);
        }
        else if(errorPhone){
            JOptionPane.showMessageDialog(this,"Please enter correct Phone number.", "Failure", JOptionPane.ERROR_MESSAGE);
        }
        
        else{
            if(!(String.valueOf(newPassword.getPassword()).equals(String.valueOf(confirmPassword.getPassword())))){
                JOptionPane.showMessageDialog(this,"Password doesn't match!!!", "Failure", JOptionPane.ERROR_MESSAGE);
            }
            else{
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog (this, "Are you sure you want to submit?","Warning",dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION){
                    java.util.Date now = new java.util.Date();
                    SimpleDateFormat dateFormatter = new SimpleDateFormat("EEE, MMM d, yyyy 'at' hh:mm:ss a zzz");
                    String date = dateFormatter.format(now);
                    try{
                        Class.forName("com.mysql.cj.jdbc.Driver");
                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/cse?serverTimezone=EST5EDT", "root", "");
                        String sql = "insert into user_info values (?, ?, ?, ?, ?, ?, ?, ?)";
                        PreparedStatement p = conn.prepareStatement(sql);

                        p.setString(1, userName.getText());
                        p.setString(2, encrypt(name.getText().trim(),secretKey));
                        p.setString(3, encrypt(phone.getText().trim(),secretKey));
                        p.setString(4, hashPassword(String.valueOf(newPassword.getPassword()).trim()));
                        p.setString(5, encrypt(email.getText().trim(),secretKey));     
                        p.setString(6, date);
                        p.setString(7, date);
                        p.setString(8, "no");
                        p.executeUpdate();
                        JOptionPane.showMessageDialog(this,"Registration Successful.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
                        //updateComboBox();
                        cancel.doClick();
                    }catch(Exception ex){ JOptionPane.showMessageDialog(this,ex); }
                }
            }

        }
        
    }//GEN-LAST:event_registerActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        name.setText("");
        nameFocusLost();
        phone.setText("");
        phoneFocusLost();
        userName.setText("");
        userNameFocusLost();
        newPassword.setText("");
        newPasswordFocusLost();
        confirmPassword.setText("");
        confirmPasswordFocusLost();
        new Login_2().setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void showPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassword1ActionPerformed
        // TODO add your handling code here:
        if(!(String.valueOf(newPassword.getPassword()).equals("New password")) && !(String.valueOf(confirmPassword.getPassword()).equals("Confirm password"))){
            if(showPassword1.isSelected()){
                newPassword.setEchoChar((char) 0);
                confirmPassword.setEchoChar((char) 0);
                newPassword.setFont(new java.awt.Font("Tahoma", 1, 14));
                confirmPassword.setFont(new java.awt.Font("Tahoma", 1, 14));
            }
            else{
                newPassword.setForeground(Color.black);
                confirmPassword.setForeground(Color.black);
                newPassword.setEchoChar('\u25cf');
                confirmPassword.setEchoChar('\u25cf');
                newPassword.setFont(new java.awt.Font("Tahoma", 1, 14));
                confirmPassword.setFont(new java.awt.Font("Tahoma", 1, 14));
            }
        }

    }//GEN-LAST:event_showPassword1ActionPerformed

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if(email.getText().trim().equals("Enter Email address")){
            email.setText("");
            email.setForeground(Color.black);
            email.setFont(new java.awt.Font("Tahoma", 1, 14));
        }
    }//GEN-LAST:event_emailFocusGained
    void emailFocusLost(){
        if(email.getText().trim().equals("")){
            email.setText("Enter Email address");
            email.setForeground(new Color(204,204,204));
            email.setFont(new java.awt.Font("Tahoma", 3, 14));
        }
        if(!(email.getText().trim().equals("")) && !(email.getText().trim().equals("Enter Email address"))){
            if (!(email.getText().contains("@gmail.com")) && !(email.getText().contains("@yahoo.com")) && !(email.getText().contains("@outlook.com"))) {
                //JOptionPane.showMessageDialog(this,"Invalid email.", "ERROR", JOptionPane.ERROR_MESSAGE); 
                emailError.setText("Invalid Email.");
                errorEmail = true;
                //email.setText("");
                //emailFocusLost();
            }
            else { emailError.setText(" "); errorEmail = false; }
        }
        else { emailError.setText(" "); errorEmail = false; }
    }
    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        emailFocusLost();        
    }//GEN-LAST:event_emailFocusLost

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
            if(phone.getText().length() < 13) {   phoneError.setText(""); errorPhone = false; return;  }
        }
        if(!(phone.getText().equals(""))){  
            if(phone.getText().length() > 10) { phoneError.setText("Max limit over."); errorPhone = true; }  
            else { 
                try{     
                    long i = Integer.parseInt(phone.getText());
                    phoneError.setText("");
                    errorPhone = false;
                }catch(Exception e){ phoneError.setText("Invalid phone number."); errorPhone = true; }           
            }
        }       
    }//GEN-LAST:event_phoneKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_New().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailError;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phoneError;
    private javax.swing.JButton register;
    private javax.swing.JCheckBox showPassword1;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
